### PR TITLE
Added Flutter 2.x support to Zefyr

### PR DESCRIPTION
**Pull request by Amir-P**
Some of the widget tests are not passing. As far as I found out it isn't because of mine or Flutter 2.x changes. It will be good if you could check it out.
Also the Notus version in pubspec should be changed because of the meta package conflict which was fixed in #511.

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
Thanks!
Just to clarify: you are running Flutter `stable` branch, not master or dev?
I'll checkout this branch tomorrow and see what's wrong with the tests.

**Comment by Amir-P** [comment]
> Thanks!
> 
> Just to clarify: you are running Flutter `stable` branch, not master or dev?
> 
> I'll checkout this branch tomorrow and see what's wrong with the tests.

Yes, I'm on the `stable` channel. Thanks! I'll be waiting for your response.

**Comment by pulyaevskiy** [comment]
I do have some changes to address broken tests but I can't push to your branch as I don't have required permissions. Could you update this PR to "Allow edits from maintainers"?

**Comment by Amir-P** [comment]
> I do have some changes to address broken tests but I can't push to your branch as I don't have required permissions. Could you update this PR to "Allow edits from maintainers"?

Unfortunately this option is not available for forks in organization accounts. Is there anything else we can do?

**Comment by pulyaevskiy** [comment]
@Amir-P I invited you as collaborator to this repo, you might have to do the same for the Taskulu fork. Not sure if it'll help though. I'll try to suggest edits in review as well...

**Comment by Amir-P** [comment]
> @Amir-P I invited you as collaborator to this repo, you might have to do the same for the Taskulu fork. Not sure if it'll help though. I'll try to suggest edits in review as well...

Done @pulyaevskiy .

**Comment by pulyaevskiy** [comment]
I think the build is failing because it runs against Flutter's master branch, which contains some more breaking changes. Tests pass on the stable branch now.

**Review by pulyaevskiy — APPROVED** [review]
LGTM

**Pull request merged**
