### PR TITLE
Add support for clicking links when viewing documents

### PR DESCRIPTION
**Pull request by cgestes**
I added an AttrDelegate but you may want to do it another way. Feel free to give me some guidance.

How to use:
```dart
class CustomAttrDelegate implements ZefyrAttrDelegate {
  CustomAttrDelegate();

  @override
  void onLinkTap(String value) {
    print('the link is: ${value}');
  }
}

ZefyrView(document: myDoc,
                attrDelegate: CustomAttrDelegate());
```

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
This is a nice approach overall and I was planning to do something along these lines. Going this route would help to get rid of url_launcher dependency in Zefyr and leave this behavior to the user.

Won't merge it right now as this would conflict with my near term changes. Will keep it open as a reference though.

**Comment by badaween-ahmed** [comment]
How to launch url of embedded link?

@cgestes There is no such parameter `attrDelegate` in `ZefyrView()`; Also I can't Find any class named  `ZefyrAttrDelegate`.

**Comment by ishandeveloper** [comment]
> 
> 
> I added an AttrDelegate but you may want to do it another way. Feel free to give me some guidance.
> 
> How to use:
> 
> ```dart
> class CustomAttrDelegate implements ZefyrAttrDelegate {
>   CustomAttrDelegate();
> 
>   @override
>   void onLinkTap(String value) {
>     print('the link is: ${value}');
>   }
> }
> 
> ZefyrView(document: myDoc,
>                 attrDelegate: CustomAttrDelegate());
> ```

#### I was just looking for something similar to this. I tried your solution and it works like a charm, 
Thanks for this! ✨

**Comment by cgestes** [comment]
Core rewrite in branch 1.0-dev (see https://github.com/memspace/zefyr/issues/409) makes this PR irrelevant. 

See ZefyrEditor onLaunchUrl property or future evolution in the 1.0-dev git branch

**Pull request closed without merging**
