### PR TITLE
Added mention support

### PR DESCRIPTION
**Pull request by Amir-P**

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
This is impressive, but also a lot of changes. 👍  I'll be taking a closer look during the week. Sorry for the delay here.

**Comment by Amir-P** [comment]
@pulyaevskiy 
I just applied some changes and fixed a lot of issues in my previous commit. Issues that I wasn't able to fix:

1. `A OverlayEntry was used after being disposed.` error after selecting one of the suggestions for mentioning.
2. Deletion and insertion inside of one of two consecutive mentions with the same value causes both of them to lose mention attribute.

Please let me know if you have any idea on how to fix these issues. Thanks.

**Comment by cgestes** [comment]
On Mon, Oct 18, 2021, 06:48 Amir Panahandeh ***@***.***>
wrote:

> Tried your patchset, impressive.
>
> On Linux the suggestion list overlay is not always placed correctly. I
> suspect some tweaks needs to be done with the overlay window :D
>
> Thanks. It's not tested on desktop and web yet. I will try to fix it.
>
It seems to miss accounting for where the Zefyr Widget is positionned on
the page.

> Also I think it shoudl've implemented using embeddables but since inline
> embed is not supported in Zefyr yet, this is the only way for now.
>
May not be so hard to do. Would make sense for links also, to be able to
adapt the behavior perfectly.
I can give it a look if you want.

**Comment by mohammedX6** [comment]
Hi, Why this branch is deleted ?, I want to support mention feature in my app.

**Comment by Amir-P** [comment]
Shoot! I accidently tapped on delete branch!

I will add it again. @mohammedX6

**Pull request closed without merging**
