### PR TITLE
Better experience with SelectionHandles

### PR DESCRIPTION
**Pull request by amantoux**
Experience closer to TextField when dragging handles

### CODE REVIEW

**Comment by amantoux** [comment]
Don't understand why the build failed here.
Any ideas anyone?

**Comment by pulyaevskiy** [comment]
Thanks for the PR. Could you describe how this improves experience? Some steps to reproduce and/or screen recordings would be really helpful.

**Comment by cgestes** [comment]
It allows to actually drag the handlers :) (before it would not move most
of the time, especially the first one)

**Comment by amantoux** [comment]
Also, when the user is in the process of dragging a handle, if the drag update falls outside a paragraph, the selection still captures the `dx` component of the drag update, it is a standard behaviour in text selection

**Pull request merged**
