### PR TITLE
Double tap on a word selects it in addition to long press

### PR DESCRIPTION
**Pull request by amantoux**
Selecting a word by double tapping on it is quite standard.
Adding this feature while preserving long press action

### CODE REVIEW

**Comment by cgestes** [comment]
Should we use TextSelectionGestureDetector: https://github.com/flutter/flutter/blob/82eeb94045d22d358e1969d09b8b68835498137f/packages/flutter/lib/src/widgets/text_selection.dart

to get double click, and selection with the mouse ?

**Comment by cgestes** [comment]
why is it closed?

**Comment by amantoux** [comment]
> why is it closed?
Wrongly closed

**Comment by amantoux** [comment]
Closing -> resolved with #329

**Comment by amantoux** [comment]
> Should we use TextSelectionGestureDetector: https://github.com/flutter/flutter/blob/82eeb94045d22d358e1969d09b8b68835498137f/packages/flutter/lib/src/widgets/text_selection.dart
> 
> to get double click, and selection with the mouse ?

I'll propose something in another PR for the selection

**Pull request closed without merging**
