### PR TITLE
Fix potential null dereference

### PR DESCRIPTION
**Pull request by cgestes**
should it be an assert instead?

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
Just a quick update I'm still looking for a way to reproduce this issue. Merging this without adding a test is not very comfortable...

**Comment by pulyaevskiy** [comment]
> should it be an assert instead?

Can definitely change this to an assert. Would be ok to merge without a test. Though it won't fix the underlying problem.

**Comment by Faiyyaz** [comment]
I just write a text and do select all on iOS and try to add a link and error comes in the log

**Comment by cgestes** [comment]
Core rewrite in branch 1.0-dev (see https://github.com/memspace/zefyr/issues/409) makes this PR irrelevant.

**Pull request closed without merging**
