### PR TITLE
Inline toggle style feature

### LINKED ISSUE #20: Change bold and italic to toggle on/off
I would suggest to change the bold and italic text style buttons to toggle their respective styles on or off for all following entries. 

The current implementation only allows for changing currently marked text to bold/italic, it however makes things very complicated if you mark your last typed text as bold/italic, since this means that all following text is automatically marked as bold or italic without the simple option to turn it off again.

IMHO the option to mark selected text as bold or italic should be kept, if no text is currently selected however the respective buttons should toggle the text styles on/off as described above.

### PR DESCRIPTION
**Pull request by jolancornevin**
Fixes #20

### CODE REVIEW

**Comment by jolancornevin** [comment]
It looks like the build failed, but I'm unsure why?

**Comment by jolancornevin** [comment]
Hi!

Thanks for your feedback! I agree with everything except for the `Map<NotusAttribute, int>` part. I think that my solution is better because it's more performant to lookup and update (as I use the index of the cursor as an index of the map) and it's already doing what you are proposing (being able to toggle both attributes at the same index) as I'm using a NotusStyle to store all attributes properly.

I've made a GIF to show you what it looks like:
toggledFeatureDemo

I'll be glad to change anything you don't like :)

**Comment by jolancornevin** [comment]
That was not how I was seeing this behaviour, but after testing on a different platform, you are actually right! And it actually makes the code much cleaner!

So I followed your advice and only took the liberty to not Reset `toggledStyles` to `null` but to reset it to a `new NotusStyle` instead to make it easier to update it when needed (instead of having to test for null).

Here's a GIF of the updated behaviour:
toggledFeatureDemo

FYI, I still don't understand why my builds fail, if you have any hint for me.

**Comment by pulyaevskiy** [comment]
Re: build failure. You need to run dartfmt to format your changes. I normally have dartfmt run on every file save in my IDE.

I think both vscode and IntelliJ have a setting to format on save. The file you need to fix is controller.dart 

I’ll look at the updates later today. Thanks for working on this again!

**Comment by jolancornevin** [comment]
Awesome!

**Comment by jolancornevin** [comment]
Thanks for your help! I'll most likely submit more PRs in the future if you don't mind because I have a lot of ideas!

**Pull request merged**
