### PR TITLE
Right now a compile time error is coming up when you try to run the c…

### PR DESCRIPTION
**Pull request by raviganwal**
…ode, So I made a few changes in order to make it run.

Compiler message:
lib/main.dart:18:9: Error:Compiler message:
lib/main.dart:18:9: Error: The superclass, 'Intent', has no unnamed constructor that takes no arguments.
  const FakeFocusIntent();
        ^^^^^^^^^^^^^^^

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
Are you on Flutter master? If you upgrade to latest master there the error should go away...

**Comment by cgestes** [comment]
LGTM.

This is with flutter master. I fixed this issue multiples times... but I guess I lost the fix while rebasing... sorry about that.

**Comment by pulyaevskiy** [comment]
@raviganwal should we close this?

**Comment by Faiyyaz** [comment]
Can we use it without switching stable to master?

**Pull request closed without merging**
