### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by cgestes**
See the commits for details.

### CODE REVIEW

**Comment by cgestes** [comment]
It actually includes 3 commits:
- a mecanical one
- one adding a simple textfield (to compare our implementation to it). (They have many differences right now)
- one dropping keybindings for arrows keys (which apparently doesnt compile).

**Comment by cgestes** [comment]
The 3 commits got merged into one. I think they should have remained 3 commits.

Also can we automatically test that examples compile? :D

**Comment by pulyaevskiy** [comment]
I prefer to do Squash&Merge actually. These were all around the example app so seemed like a safe thing to do.

> Also can we automatically test that examples compile?

Good idea. A simple solution would probably be to add a test case in examples which simply starts the app and asserts that the main screen is rendered correctly. Then update tool/travis.sh to execute `flutter test` in example subfolder.

**Comment by pulyaevskiy** [comment]
See #321

**Comment by cgestes** [comment]
I prefer to do Squash&Merge actually. These were all around the example app so seemed like a safe thing to do.

=> Ok, to make it easy to follow the changes directly from git, can we instead get the text from all the commits in the squashed commit? and maybe a link to the PR?

**Pull request merged**
